### ISSUE TITLE
Buset di obfus semua😳

### ISSUE THREAD

**Issue by FebbAdityaN** [Ramlan404/babybot#32]
Takut dicolong, padahal diri sendiri aja nyolong😳

**Comment by SulthanAlfarisi** [comment]
Ngeriiii

**Comment by Ramlan404** [comment]
> Takut dicolong, padahal diri sendiri aja nyolong😳

Bukan takut di colong bang, gak enak kan kalo bukan hasil sendiri disebar mhehe:)

**Comment by FebbAdityaN** [comment]
Ok, berarti semua orang harus obfus script nya😅
